Training model/routes
nessy126/fullstack-team-project-back pull request #5
Opened 2022-07-13 18:32 UTC by culozik

1. Добавлена модель тренировки.
2. Добавлены маршрут старта тренировки.
3. Добавлен маршрут получения данных о тренировке.
4. В модель пользователя добавлено поле с id тренировки.

2022-07-13 21:58 UTC, nessy126 commented on controllers/training/startTraining.js
> +  if (!training) {
а что это за проверка? откуда при создании может прилететь 404? Наверное надо перед записью делать проверки того, что приходит, и если чего-то нет, то не создавать

2022-07-13 22:13 UTC, nessy126 commented on controllers/training/startTraining.js
> +    setStatus(el);
Тут наверное не весь элемент надо передавать, а только id? Ты тестировал эту функцию?

2022-07-13 22:14 UTC, nessy126 commented on controllers/training/startTraining.js
> +    setStatus(el);
Я бы вообще всю функцию setStatus вынесла из этого контролеллера в отдельный, который будет принимать и айди и сам статус, потмоу что потом еще в прочитанные надо будет менять

2022-07-13 22:20 UTC, nessy126 commented on controllers/training/startTraining.js
> +const addTraining = async (req, res, next) => {
зачем next? Не используется же. И вроде контроллекр всегда в конце стоит

2022-07-13 22:25 UTC, nessy126 commented on models/user.js
> +    training: {
Зачем ты это сюда добавляешь? Пусть у самой тренировки будет owner, как в книге

2022-07-13 23:30 UTC, nessy126 commented on models/training.js
> +    amountOfDays: {
я думаю это фронте пусть будет

2022-07-13 23:36 UTC, nessy126 requested changes
надо пообщаться, может втроем с Леной

2022-07-14 06:51 UTC, culozik commented on controllers/training/startTraining.js
> +    setStatus(el);
1. В массиве training.books как раз находятся id книг, которые в коллекции. Да, тестировал, работает.
2. Окей. Вынесем в отдельную. Я только ее обьявил и тестировал только в контроллере старта тренировки.

2022-07-14 06:53 UTC, culozik commented on controllers/training/startTraining.js
> +const addTraining = async (req, res, next) => {
В параметрах указал, если применяться не будет - уберу с параметров.

2022-07-14 06:54 UTC, culozik commented on controllers/training/startTraining.js
> +  if (!training) {
Это проверка на тот случай,  если мои создании происходит ошибка. Здесь как раз 404 не прилетает, а наоборот генерируется в случае неудачного создания новой тренировки.

2022-07-14 06:56 UTC, culozik commented on models/training.js
> +    amountOfDays: {
Сообщения об ошибке пусть останутся. Обработчик ошибок Магнуса запустится только в том случае, если все предыдущие проверки не отработали. На производительность в данном случае не влияет, а как дополнительная Страховка не помешает.

2022-07-14 06:58 UTC, culozik commented on models/user.js
> +    training: {
Это нужно для того, что бы при переходе на страницу тренировки получать данные тренировки конкретного юзера, не по книге искать какой южно и какая у него тренировка, а у юзера смотреть какая у него сейчас тренировка, и обращаться именно к объекту той тренировки.

2022-07-14 07:00 UTC, nessy126 commented on models/training.js
> +    books: [
booksId

2022-07-14 07:06 UTC, nessy126 commented on models/training.js
> +          min: 0,
зачем 0 в дате?

2022-07-14 07:08 UTC, nessy126 commented on models/training.js
> +          min: 0,
добавь еще время пожалуйста

2022-07-14 13:04 UTC, nessy126 commented on models/training.js
> +          min: 0,
min 1

2022-07-15 10:07 UTC, culozik commented on controllers/training/startTraining.js
> +    setStatus(el);
Функция setStatus  переписана с использованием Query.prototype.updateMany().

2022-07-15 10:07 UTC, culozik commented on controllers/training/startTraining.js
> +const addTraining = async (req, res, next) => {
Убрал next.

2022-07-15 10:10 UTC, culozik commented on models/user.js
> +    training: {
У модели тренировки теперь есть поле owner.
В модели user нет поля training.

2022-07-15 10:10 UTC, culozik commented on models/training.js
> +    books: [
Сделано

2022-07-15 10:10 UTC, culozik commented on models/training.js
> +          min: 0,
Сделано.

2022-07-15 10:37 UTC, OlenaPatlata approved these changes

2022-07-15 10:40 UTC, OlenaPatlata approved these changes

2022-07-15 16:17 UTC, nessy126 approved these changes

2022-07-15 16:17 UTC, nessy126 commented on controllers/training/trainingProgress.js
> +  const booksLeft = booksList.filter(el => el.status === 'inReading').length;
Назови его booksInReading

2022-07-15 16:17 UTC, nessy126 commented on models/training.js
> +          min: 0,
Решили вчера с Богданом, что когда тренировка уходит  в минус, она автоматически завершается.
И нужно добавить поле тут и на фронте, treiningStatus

2022-07-15 16:17 UTC, nessy126 commented on models/training.js
> +          min: 0,
Tam I'll inAtive ili finished

2022-07-15 16:17 UTC, nessy126 commented on models/training.js
> +    isTrainingActive: {
Вместо вот этого то другое поле

2022-07-15 16:17 UTC, nessy126 commented on controllers/training/startTraining.js
> +const addTraining = async ({ user: { _id }, body }, res) => {
req

2022-07-15 16:17 UTC, nessy126 commented on controllers/training/trainingProgress.js
> +const trainingProgress = async ({ user: { _id } }, res) => {
req

2022-07-15 16:17 UTC, nessy126 commented on controllers/training/trainingProgress.js
> +  res.status(200).json({
добавить объект

2022-07-15 16:17 UTC, merged